
# the first step of the pipeline
# is "bcftools norm" that also
# checks the reference allele;
# specify here how mismatches
# between vcf and the reference
# FASTA should be handled
# s - [s]et to ref FASTA
# e - [e]xit immediately
# w - [w]arning
# x - e[x]clude records
vcf_norm_ref_action: s

# Config options to use reference container
# as part of the pipeline
use_reference_container: false
# If use_reference_container is set to true, the following
# two options must be specified as well in the config

# Existing path to directory with reference container (*.sif) files.
# This option is specific to the execution infrastructure.
# reference_container_store: <PATH>

# List of container names to be used in the pipeline
# reference_container_names:
#   - name1
#   - name2
