
# Example config for reference
# genomes and annotations to
# use during VCF annotation

reference_genomes:
  ref1: plain_fasta_file.fasta
  ref2: plain_fasta_file.fasta

reference_chromosomes:
  - list
  - of
  - reference
  - chromosomes
  - to
  - use;
  - applies
  - to
  - all
  - reference_genomes


annotations:
  ref1:
    bed1: ref1.bedfile1.bed
    bed2: ref1.bedfile2.bed
    bed3: ref1.bedfile3.bed
  ref2:
    bed1: ref2.bedfile1.bed
    bed2: ref2.bedfile2.bed

